#!/bin/bash

# This winbox(Mikrotik Controller) program is Free for all
# Created by Myat Min Oo(D4RKN37)

# winbox application is only for Windows Programs
# and now winbox application use in Linux
# First, we need to install wine

# we need to download winbox.exe file from www.mikrotik.com website 
wget -O /usr/share/winbox/winbox.exe https://download.mikrotik.com/routeros/winbox/3.16/winbox.exe

wine /usr/share/winbox/winbox.exe 
